services:
  localstack:
    image: localstack/localstack:latest
    container_name: t2r-ls
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - EAGER_SERVICE_LOADING=1
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
  postgres:
    image: postgres:latest
    container_name: t2r-pg
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: t2r-pg
      POSTGRES_USER: t2r-user
      POSTGRES_PASSWORD: t2r-pass
    volumes:
      - "db_data:/var/lib/postgresql/data"
    depends_on:
      - localstack
volumes:
  db_data:
    driver: local

