create table tb_talker_type (
    id bigint generated by default as identity not null,
    description character varying not null
);

alter table tb_talker_type
    add constraint pk_tb_talker_type primary key (id);

alter table tb_talker_type
    add constraint uc_tb_talker_type_description unique (description);

insert into tb_talker_type values (1, 'collaborator');

insert into tb_talker_type values (2, 'immigrant');

insert into tb_talker_type values (3, 'refugee');